
INSERT INTO tour_packages (id, package_name, description, price, duration, image_url, location) VALUES
(1, 'Golden Triangle - Delhi-Agra-Jaipur', 'Classic 5-day tour covering Delhi, Agra and Jaipur. Includes sightseeing and hotel stay.', 250.0, '5 days', 'https://example.com/images/golden_triangle.jpg', 'Delhi/Agra/Jaipur'),
(2, 'Goa Beach Delight', 'Relaxing 4-day beach holiday in Goa with optional water sports.', 180.0, '4 days', 'https://example.com/images/goa.jpg', 'Goa'),
(3, 'Himachal Adventure', '7-day hill station tour covering Manali and Shimla with trekking options.', 420.0, '7 days', 'https://example.com/images/himachal.jpg', 'Himachal Pradesh');


CREATE TABLE `USER` ( `ID` BIGINT NOT NULL AUTO_INCREMENT, `FIRST_NAME` VARCHAR(255), `LAST_NAME` VARCHAR(255), `FULL_NAME` VARCHAR(255), `NUMBER` VARCHAR(255), `USER_NAME` VARCHAR(255), `PASSWORD` VARCHAR(255), `CREATED_DATE` DATETIME, PRIMARY KEY (`ID`) );

CREATE TABLE `CATEGORY` ( `ID` BIGINT NOT NULL AUTO_INCREMENT, `NAME` VARCHAR(255), `DESCRIPTION` VARCHAR(255), `ICON` VARCHAR(255), `STATUS` BOOLEAN, `BACKGROUND_COLOR` VARCHAR(255), PRIMARY KEY (`ID`) );

CREATE TABLE `PACKAGES` ( `ID` BIGINT NOT NULL AUTO_INCREMENT, `NAME` VARCHAR(255), `DESCRIPTION` VARCHAR(255), `MAJOR_ATTRACTIONS_LIST` VARCHAR(255), `INCLUSIONS_FOR_CARD` VARCHAR(255), `IMAGE_URL` VARCHAR(255), `DESTINATION` VARCHAR(255), `MEMBERS` VARCHAR(255), `AMOUNT` DOUBLE, `TOTAL_DAYS` INT, `STATUS` BOOLEAN, `INCLUSION` VARCHAR(255), `EXCLUSION` VARCHAR(255), `HOTEL` VARCHAR(255), `FLIGHT` VARCHAR(255), `BADGE` VARCHAR(255), `PACKAGE_COLOR` VARCHAR(255), `PACKAGE_UNIQUE_CODE` VARCHAR(255), `TRAVEL_TYPE` VARCHAR(3), `IS_COMPLETED` BOOLEAN, PRIMARY KEY (`ID`) );

CREATE TABLE `BLOGS` ( `ID` BIGINT NOT NULL AUTO_INCREMENT, `TITLE` VARCHAR(255), `SLUG` VARCHAR(255), `EXCERPT` VARCHAR(255), `CONTENT` LONGTEXT, `COVER_IMAGE` VARCHAR(255), `STATUS` VARCHAR(255), `PUBLISH_AT` DATETIME, `CREATED_AT` DATETIME, `UPDATED_AT` DATETIME, PRIMARY KEY (`ID`) );

CREATE TABLE `PACKAGES_CATEGORY_MAPPING` ( `ID` BIGINT NOT NULL AUTO_INCREMENT, `PACKAGE_ID` BIGINT, `CATEGORY_ID` BIGINT, `ACTIVE` VARCHAR(255), PRIMARY KEY (`ID`) );

CREATE TABLE `ACTIVITIES` ( `ID` BIGINT NOT NULL AUTO_INCREMENT, `PACKAGE_ID` BIGINT, `day` INT, `header` VARCHAR(255), `points` VARCHAR(255), PRIMARY KEY (`ID`) );

CREATE TABLE `CONTACT_INQUIRY` ( `ID` BIGINT NOT NULL AUTO_INCREMENT, `NAME` VARCHAR(255), `EMAIL` VARCHAR(255), `NUMBER` VARCHAR(12), `PERSION_COUNT` INT, `MESSAGE` VARCHAR(255), `INQUIRY_CODE` VARCHAR(20), `PACKAGE_ID` BIGINT, PRIMARY KEY (`ID`) );



INSERT INTO `USER` ( `FIRST_NAME`, `LAST_NAME`, `FULL_NAME`, `NUMBER`, `USER_NAME`, `PASSWORD`, `CREATED_DATE` ) VALUES ( 'Mohit', 'Sahu', 'Mohit Sahu', 9876543210, 'mohit', '0e7517141fb53f21ee439b355b5a1d0a', NOW() );